/**
 * Tests for src/prompts.ts - Prompt templates for CLAUDE.md and documentation
 */
import { describe, it, expect } from "vitest";
import {
  generateHarnessSection,
  generateClaudeMd,
  generateCommitMessage,
  generateFeatureGuidance,
  generateImpactGuidance,
  generateSessionSummary,
} from "../src/prompts.js";

describe("Prompts", () => {
  describe("generateHarnessSection", () => {
    it("should generate harness section with project goal", () => {
      const goal = "Build a todo app";
      const section = generateHarnessSection(goal);

      expect(section).toContain("## Long-Task Harness");
      expect(section).toContain("Build a todo app");
      expect(section).toContain("### Project Goal");
    });

    it("should include core files table", () => {
      const section = generateHarnessSection("Test goal");

      expect(section).toContain("### Core Files");
      expect(section).toContain("| File | Purpose |");
      expect(section).toContain("`ai/feature_list.json`");
      expect(section).toContain("`ai/progress.md`");
      expect(section).toContain("`ai/init.sh`");
    });

    it("should include feature status values", () => {
      const section = generateHarnessSection("Test goal");

      expect(section).toContain("### Feature Status Values");
      expect(section).toContain("`failing`");
      expect(section).toContain("`passing`");
      expect(section).toContain("`blocked`");
      expect(section).toContain("`needs_review`");
      expect(section).toContain("`deprecated`");
    });

    it("should include workflow steps", () => {
      const section = generateHarnessSection("Test goal");

      expect(section).toContain("### Workflow for Each Session");
      expect(section).toContain("1. **Start**");
      expect(section).toContain("2. **Select**");
      expect(section).toContain("3. **Plan**");
      expect(section).toContain("4. **Implement**");
      expect(section).toContain("5. **Test**");
      expect(section).toContain("6. **Complete**");
      expect(section).toContain("7. **Log**");
      expect(section).toContain("8. **Next**");
    });

    it("should include rules section", () => {
      const section = generateHarnessSection("Test goal");

      expect(section).toContain("### Rules");
      expect(section).toContain("One feature per session");
      expect(section).toContain("Don't modify acceptance criteria");
      expect(section).toContain("Update status promptly");
      expect(section).toContain("Leave clean state");
    });

    it("should include progress log format", () => {
      const section = generateHarnessSection("Test goal");

      expect(section).toContain("### Progress Log Format");
      expect(section).toContain("STEP");
      expect(section).toContain("CHANGE");
      expect(section).toContain("REPLAN");
      expect(section).toContain("single-line format");
    });

    it("should include CLI commands", () => {
      const section = generateHarnessSection("Test goal");

      expect(section).toContain("### Commands");
      expect(section).toContain("agent-foreman status");
      expect(section).toContain("agent-foreman step");
      expect(section).toContain("agent-foreman impact");
      expect(section).toContain("./ai/init.sh bootstrap");
      expect(section).toContain("./ai/init.sh dev");
      expect(section).toContain("./ai/init.sh check");
    });

    it("should include feature ID convention", () => {
      const section = generateHarnessSection("Test goal");

      expect(section).toContain("### Feature ID Convention");
      expect(section).toContain("dot notation");
      expect(section).toContain("`auth.login`");
      expect(section).toContain("`chat.message.edit`");
      expect(section).toContain("`api.users.create`");
    });

    it("should include acceptance criteria format", () => {
      const section = generateHarnessSection("Test goal");

      expect(section).toContain("### Acceptance Criteria Format");
      expect(section).toContain("testable statements");
    });

    it("should include feature JSON schema", () => {
      const section = generateHarnessSection("Test goal");

      expect(section).toContain("### Feature JSON Schema");
      expect(section).toContain('"id": "module.feature.action"');
      expect(section).toContain('"status": "failing"');
      expect(section).toContain('"acceptance"');
      expect(section).toContain('"dependsOn"');
      expect(section).toContain("Required fields");
      expect(section).toContain("Status values");
      expect(section).toContain("Origin values");
    });

    it("should include generator attribution", () => {
      const section = generateHarnessSection("Test goal");

      expect(section).toContain("Generated by agent-foreman");
      expect(section).toContain("https://github.com/mylukin/agent-foreman");
    });

    it("should handle empty goal", () => {
      const section = generateHarnessSection("");

      expect(section).toContain("### Project Goal");
      expect(section).toContain("## Long-Task Harness");
    });

    it("should handle goal with special characters", () => {
      const goal = "Build a *special* app with `code` and <html>";
      const section = generateHarnessSection(goal);

      expect(section).toContain(goal);
    });
  });

  describe("generateClaudeMd", () => {
    it("should generate complete CLAUDE.md content", () => {
      const content = generateClaudeMd("My project goal");

      expect(content).toContain("# Project Instructions");
      expect(content).toContain("## Long-Task Harness");
      expect(content).toContain("My project goal");
    });

    it("should include harness section", () => {
      const content = generateClaudeMd("Test");

      expect(content).toContain("### Core Files");
      expect(content).toContain("### Feature Status Values");
      expect(content).toContain("### Workflow for Each Session");
    });

    it("should start with markdown header", () => {
      const content = generateClaudeMd("Test");

      expect(content.startsWith("# Project Instructions")).toBe(true);
    });
  });

  describe("generateCommitMessage", () => {
    it("should generate commit message with feature info", () => {
      const message = generateCommitMessage(
        "auth.login",
        "Add user login",
        "Implemented login form with validation"
      );

      expect(message).toContain("feat(auth): Add user login");
      expect(message).toContain("Implemented login form with validation");
      expect(message).toContain("Feature: auth.login");
    });

    it("should extract module from feature ID", () => {
      const message = generateCommitMessage(
        "api.users.create",
        "Create user endpoint",
        "Summary"
      );

      expect(message).toContain("feat(api):");
    });

    it("should include generator attribution", () => {
      const message = generateCommitMessage("test.feature", "Test", "Summary");

      expect(message).toContain("Generated with agent-foreman");
    });

    it("should handle single-segment feature ID", () => {
      const message = generateCommitMessage("core", "Core feature", "Summary");

      expect(message).toContain("feat(core):");
    });
  });

  describe("generateFeatureGuidance", () => {
    it("should generate guidance with feature details", () => {
      const feature = {
        id: "auth.login",
        description: "User login functionality",
        acceptance: ["User can enter credentials", "User sees success message"],
        dependsOn: [],
        notes: "",
      };

      const guidance = generateFeatureGuidance(feature);

      expect(guidance).toContain("## Feature: auth.login");
      expect(guidance).toContain("**Description:** User login functionality");
    });

    it("should list acceptance criteria with checkboxes", () => {
      const feature = {
        id: "test",
        description: "Test",
        acceptance: ["First criterion", "Second criterion", "Third criterion"],
        dependsOn: [],
        notes: "",
      };

      const guidance = generateFeatureGuidance(feature);

      expect(guidance).toContain("### Acceptance Criteria");
      expect(guidance).toContain("1. [ ] First criterion");
      expect(guidance).toContain("2. [ ] Second criterion");
      expect(guidance).toContain("3. [ ] Third criterion");
    });

    it("should include dependencies section when present", () => {
      const feature = {
        id: "auth.profile",
        description: "User profile",
        acceptance: ["Criterion"],
        dependsOn: ["auth.login", "auth.register"],
        notes: "",
      };

      const guidance = generateFeatureGuidance(feature);

      expect(guidance).toContain("### Dependencies");
      expect(guidance).toContain("Ensure these features are passing first:");
      expect(guidance).toContain("- auth.login");
      expect(guidance).toContain("- auth.register");
    });

    it("should not include dependencies section when empty", () => {
      const feature = {
        id: "test",
        description: "Test",
        acceptance: ["Criterion"],
        dependsOn: [],
        notes: "",
      };

      const guidance = generateFeatureGuidance(feature);

      expect(guidance).not.toContain("### Dependencies");
    });

    it("should include notes section when present", () => {
      const feature = {
        id: "test",
        description: "Test",
        acceptance: ["Criterion"],
        dependsOn: [],
        notes: "Important implementation note",
      };

      const guidance = generateFeatureGuidance(feature);

      expect(guidance).toContain("### Notes");
      expect(guidance).toContain("Important implementation note");
    });

    it("should not include notes section when empty", () => {
      const feature = {
        id: "test",
        description: "Test",
        acceptance: ["Criterion"],
        dependsOn: [],
        notes: "",
      };

      const guidance = generateFeatureGuidance(feature);

      expect(guidance).not.toContain("### Notes");
    });

    it("should include workflow section", () => {
      const feature = {
        id: "auth.login",
        description: "Test",
        acceptance: ["Criterion"],
        dependsOn: [],
        notes: "",
      };

      const guidance = generateFeatureGuidance(feature);

      expect(guidance).toContain("### Workflow");
      expect(guidance).toContain("1. Review acceptance criteria above");
      expect(guidance).toContain("2. Implement the feature");
      expect(guidance).toContain("3. Run `./ai/init.sh check` to verify");
      expect(guidance).toContain("4. Run `agent-foreman complete");
      expect(guidance).toContain("(auto-verifies + commits)");
    });
  });

  describe("generateImpactGuidance", () => {
    it("should generate guidance for no affected features", () => {
      const guidance = generateImpactGuidance("auth.login", []);

      expect(guidance).toContain("## Impact Review: auth.login");
      expect(guidance).toContain("No other features are affected");
    });

    it("should list affected features in table", () => {
      const affected = [
        { id: "auth.profile", reason: "Depends on login" },
        { id: "auth.settings", reason: "Uses auth token" },
      ];

      const guidance = generateImpactGuidance("auth.login", affected);

      expect(guidance).toContain("## Impact Review: auth.login");
      expect(guidance).toContain("| Feature | Reason | Action |");
      expect(guidance).toContain("| auth.profile | Depends on login | Review and update status |");
      expect(guidance).toContain("| auth.settings | Uses auth token | Review and update status |");
    });

    it("should include recommended actions", () => {
      const affected = [{ id: "test", reason: "Test reason" }];

      const guidance = generateImpactGuidance("feature", affected);

      expect(guidance).toContain("### Recommended Actions");
      expect(guidance).toContain("1. Review each affected feature");
      expect(guidance).toContain("2. Run tests for affected modules");
      expect(guidance).toContain("3. Mark as `needs_review`");
      expect(guidance).toContain("4. Update `notes` field");
    });
  });

  describe("generateSessionSummary", () => {
    it("should generate summary with completed features", () => {
      const completed = [
        { id: "auth.login", description: "User login" },
        { id: "auth.register", description: "User registration" },
      ];

      const summary = generateSessionSummary(completed, [], null);

      expect(summary).toContain("## Session Summary");
      expect(summary).toContain("### Completed This Session");
      expect(summary).toContain("- ✅ auth.login: User login");
      expect(summary).toContain("- ✅ auth.register: User registration");
    });

    it("should show remaining feature count", () => {
      const remaining = [
        { id: "auth.profile", priority: 2 },
        { id: "auth.settings", priority: 3 },
        { id: "auth.logout", priority: 4 },
      ];

      const summary = generateSessionSummary([], remaining, null);

      expect(summary).toContain("### Remaining: 3 features");
    });

    it("should show next feature when available", () => {
      const next = { id: "auth.login", description: "User login functionality" };

      const summary = generateSessionSummary([], [], next);

      expect(summary).toContain("### Next Up");
      expect(summary).toContain("**auth.login**: User login functionality");
    });

    it("should show completion message when no next feature", () => {
      const summary = generateSessionSummary([], [], null);

      expect(summary).toContain("All features are complete!");
    });

    it("should handle empty completed list", () => {
      const summary = generateSessionSummary([], [], null);

      expect(summary).not.toContain("### Completed This Session");
    });

    it("should show full session with all sections", () => {
      const completed = [{ id: "auth.login", description: "Login" }];
      const remaining = [{ id: "auth.profile", priority: 2 }];
      const next = { id: "auth.register", description: "Registration" };

      const summary = generateSessionSummary(completed, remaining, next);

      expect(summary).toContain("### Completed This Session");
      expect(summary).toContain("### Remaining: 1 features");
      expect(summary).toContain("### Next Up");
    });
  });
});
