#!/usr/bin/env bun
/**
 * Embed Assets Script
 *
 * Reads gitignore templates and plugins, then generates TypeScript files
 * with embedded content for use in compiled binaries.
 *
 * Usage: bun scripts/embed-assets.ts
 */

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT_DIR = join(import.meta.dirname, "..");
const TEMPLATES_DIR = join(ROOT_DIR, "src/gitignore/templates");
const RULES_DIR = join(ROOT_DIR, "src/rules/templates");
const PLUGINS_DIR = join(ROOT_DIR, "plugins");
const GENERATED_TEMPLATES_FILE = join(ROOT_DIR, "src/gitignore/embedded-templates.generated.ts");
const GENERATED_RULES_FILE = join(ROOT_DIR, "src/rules/embedded-rules.generated.ts");
const GENERATED_PLUGINS_FILE = join(ROOT_DIR, "src/plugins-bundle.generated.ts");
const GENERATED_VERSION_FILE = join(ROOT_DIR, "src/version.generated.ts");

/**
 * Read all files in a directory recursively
 */
function readDirRecursive(dir: string, basePath: string = ""): Map<string, string> {
  const files = new Map<string, string>();

  if (!existsSync(dir)) {
    return files;
  }

  for (const entry of readdirSync(dir)) {
    const fullPath = join(dir, entry);
    const relativePath = basePath ? `${basePath}/${entry}` : entry;
    const stat = statSync(fullPath);

    if (stat.isDirectory()) {
      const subFiles = readDirRecursive(fullPath, relativePath);
      for (const [path, content] of subFiles) {
        files.set(path, content);
      }
    } else if (stat.isFile()) {
      files.set(relativePath, readFileSync(fullPath, "utf-8"));
    }
  }

  return files;
}

/**
 * Escape string for use in TypeScript template literal
 */
function escapeForTemplateLiteral(str: string): string {
  return str
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

/**
 * Generate embedded templates TypeScript file
 */
function generateEmbeddedTemplates(): void {
  console.log("Embedding gitignore templates...");

  const templates = new Map<string, string>();

  if (!existsSync(TEMPLATES_DIR)) {
    console.warn(`Templates directory not found: ${TEMPLATES_DIR}`);
  } else {
    for (const file of readdirSync(TEMPLATES_DIR)) {
      if (file.endsWith(".gitignore")) {
        const name = file.replace(".gitignore", "");
        const content = readFileSync(join(TEMPLATES_DIR, file), "utf-8");
        templates.set(name, content);
        console.log(`  - ${name}`);
      }
    }
  }

  const templateEntries = Array.from(templates.entries())
    .map(([name, content]) => `  "${name}": \`${escapeForTemplateLiteral(content)}\``)
    .join(",\n");

  const output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by: bun scripts/embed-assets.ts
 * Generated at: ${new Date().toISOString()}
 *
 * Embedded gitignore templates for use in compiled binaries.
 */

export const EMBEDDED_TEMPLATES: Record<string, string> = {
${templateEntries}
};

export const EMBEDDED_TEMPLATE_NAMES = Object.keys(EMBEDDED_TEMPLATES);
`;

  writeFileSync(GENERATED_TEMPLATES_FILE, output, "utf-8");
  console.log(`Generated: ${relative(ROOT_DIR, GENERATED_TEMPLATES_FILE)}`);
}

/**
 * Generate embedded rules TypeScript file
 */
function generateEmbeddedRules(): void {
  console.log("\nEmbedding rules templates...");

  const rules = new Map<string, string>();

  if (!existsSync(RULES_DIR)) {
    console.warn(`Rules directory not found: ${RULES_DIR}`);
  } else {
    for (const file of readdirSync(RULES_DIR)) {
      if (file.endsWith(".md")) {
        const name = file.replace(".md", "");
        const content = readFileSync(join(RULES_DIR, file), "utf-8");
        rules.set(name, content);
        console.log(`  - ${name}`);
      }
    }
  }

  const ruleEntries = Array.from(rules.entries())
    .map(([name, content]) => `  "${name}": \`${escapeForTemplateLiteral(content)}\``)
    .join(",\n");

  const output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by: bun scripts/embed-assets.ts
 * Generated at: ${new Date().toISOString()}
 *
 * Embedded rule templates for use in compiled binaries.
 */

export const EMBEDDED_RULES: Record<string, string> = {
${ruleEntries}
};

export const EMBEDDED_RULE_NAMES = Object.keys(EMBEDDED_RULES);
`;

  writeFileSync(GENERATED_RULES_FILE, output, "utf-8");
  console.log(`Generated: ${relative(ROOT_DIR, GENERATED_RULES_FILE)}`);
}

/**
 * Generate embedded plugins TypeScript file
 */
function generateEmbeddedPlugins(): void {
  console.log("\nEmbedding plugins...");

  const files = readDirRecursive(PLUGINS_DIR);
  console.log(`  Found ${files.size} files`);

  const fileEntries = Array.from(files.entries())
    .map(([path, content]) => `  "${path}": \`${escapeForTemplateLiteral(content)}\``)
    .join(",\n");

  // Read version from package.json
  const packageJson = JSON.parse(readFileSync(join(ROOT_DIR, "package.json"), "utf-8"));
  const version = packageJson.version;

  const output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by: bun scripts/embed-assets.ts
 * Generated at: ${new Date().toISOString()}
 *
 * Embedded plugin files for auto-installation.
 */

/**
 * Current version of the embedded plugins
 */
export const EMBEDDED_PLUGINS_VERSION = "${version}";

/**
 * Map of relative file paths to their content
 * Keys are relative paths from the plugins/ directory
 */
export const EMBEDDED_PLUGINS: Record<string, string> = {
${fileEntries}
};

/**
 * Get all plugin file paths
 */
export function getEmbeddedPluginPaths(): string[] {
  return Object.keys(EMBEDDED_PLUGINS);
}

/**
 * Get plugin file content by path
 */
export function getEmbeddedPluginContent(path: string): string | undefined {
  return EMBEDDED_PLUGINS[path];
}
`;

  writeFileSync(GENERATED_PLUGINS_FILE, output, "utf-8");
  console.log(`Generated: ${relative(ROOT_DIR, GENERATED_PLUGINS_FILE)}`);
}

/**
 * Generate embedded version TypeScript file
 */
function generateEmbeddedVersion(): void {
  console.log("\nEmbedding version...");

  const packageJson = JSON.parse(readFileSync(join(ROOT_DIR, "package.json"), "utf-8"));
  const version = packageJson.version;

  const output = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by: bun scripts/embed-assets.ts
 * Generated at: ${new Date().toISOString()}
 *
 * Embedded version for use in compiled binaries.
 */

export const EMBEDDED_VERSION = "${version}";
`;

  writeFileSync(GENERATED_VERSION_FILE, output, "utf-8");
  console.log(`  Version: ${version}`);
  console.log(`Generated: ${relative(ROOT_DIR, GENERATED_VERSION_FILE)}`);
}

/**
 * Main entry point
 */
function main(): void {
  console.log("=== Embedding Assets ===\n");

  generateEmbeddedTemplates();
  generateEmbeddedRules();
  generateEmbeddedPlugins();
  generateEmbeddedVersion();

  console.log("\n=== Done ===");
}

main();
