/**
 * Generate ai/init.sh bootstrap script
 */
import type { ProjectCommands } from "./types.js";

/**
 * Generate init.sh script content
 */
export function generateInitScript(commands: ProjectCommands): string {
  return `#!/usr/bin/env bash
# ai/init.sh - Bootstrap script for agent-foreman harness
# Generated by agent-foreman
set -euo pipefail

# Colors for output
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
NC='\\033[0m' # No Color

log_info() {
  echo -e "\${GREEN}[INFO]\${NC} \$1"
}

log_warn() {
  echo -e "\${YELLOW}[WARN]\${NC} \$1"
}

log_error() {
  echo -e "\${RED}[ERROR]\${NC} \$1"
}

# Bootstrap: Install dependencies
bootstrap() {
  log_info "Installing dependencies..."
  ${commands.install || "echo 'No install command configured'"}
  log_info "Bootstrap complete!"
}

# Dev: Start development environment
dev() {
  log_info "Starting development server..."
  ${commands.dev || "echo 'No dev command configured'"}
}

# Check: Run tests and basic validation
check() {
  log_info "Running tests..."
  ${commands.test || "echo 'No test command configured'"}
  ${commands.lint ? `\n  log_info "Running lint..."\n  ${commands.lint}` : ""}
  log_info "All checks passed!"
}

# Verify: Run all available verification checks
verify() {
  local exit_code=0

  log_info "Running verification checks..."

  # Run tests if available
  ${commands.test ? `log_info "Running tests..."
  if ! ${commands.test}; then
    log_error "Tests failed"
    exit_code=1
  fi` : "log_warn \"No test command configured\""}

  # Run type check if TypeScript detected
  if [ -f "tsconfig.json" ]; then
    log_info "Running type check..."
    if ! npx tsc --noEmit; then
      log_error "Type check failed"
      exit_code=1
    fi
  fi

  # Run lint if available
  ${commands.lint ? `log_info "Running linter..."
  if ! ${commands.lint}; then
    log_error "Lint failed"
    exit_code=1
  fi` : ""}

  # Run build if available
  ${commands.build ? `log_info "Running build..."
  if ! ${commands.build}; then
    log_error "Build failed"
    exit_code=1
  fi` : ""}

  if [ \$exit_code -eq 0 ]; then
    log_info "All verification checks passed!"
  else
    log_error "Some verification checks failed"
  fi

  return \$exit_code
}

# Build: Build for production
build() {
  log_info "Building for production..."
  ${commands.build || "echo 'No build command configured'"}
  log_info "Build complete!"
}

# Status: Show project status
status() {
  log_info "Project Status"
  echo "---"

  # Show feature list status if exists
  if [ -f "ai/feature_list.json" ]; then
    echo "Feature List: ai/feature_list.json"
    local total=$(jq '.features | length' ai/feature_list.json)
    local passing=$(jq '[.features[] | select(.status == "passing")] | length' ai/feature_list.json)
    local failing=$(jq '[.features[] | select(.status == "failing")] | length' ai/feature_list.json)
    local review=$(jq '[.features[] | select(.status == "needs_review")] | length' ai/feature_list.json)
    echo "  Total: \$total"
    echo "  Passing: \$passing"
    echo "  Failing: \$failing"
    echo "  Needs Review: \$review"
  else
    log_warn "No feature list found. Run 'agent-foreman init' first."
  fi

  # Show recent progress log entries
  if [ -f "ai/progress.md" ]; then
    echo ""
    echo "Recent Progress:"
    tail -5 ai/progress.md
  fi
}

# Help
show_help() {
  echo "Usage: ./ai/init.sh <command>"
  echo ""
  echo "Commands:"
  echo "  bootstrap  Install dependencies"
  echo "  dev        Start development server"
  echo "  check      Run tests and validation"
  echo "  verify     Run all verification checks (tests, types, lint, build)"
  echo "  build      Build for production"
  echo "  status     Show project status"
  echo "  help       Show this help message"
}

# Main entry point
case "\${1:-help}" in
  bootstrap)
    bootstrap
    ;;
  dev)
    dev
    ;;
  check)
    check
    ;;
  verify)
    verify
    ;;
  build)
    build
    ;;
  status)
    status
    ;;
  help|--help|-h)
    show_help
    ;;
  *)
    log_error "Unknown command: \$1"
    show_help
    exit 1
    ;;
esac
`;
}

/**
 * Generate minimal init.sh for projects without detected commands
 */
export function generateMinimalInitScript(): string {
  return `#!/usr/bin/env bash
# ai/init.sh - Bootstrap script for agent-foreman harness
# Generated by agent-foreman
set -euo pipefail

# Colors for output
RED='\\033[0;31m'
GREEN='\\033[0;32m'
YELLOW='\\033[1;33m'
NC='\\033[0m' # No Color

log_info() {
  echo -e "\${GREEN}[INFO]\${NC} \$1"
}

log_warn() {
  echo -e "\${YELLOW}[WARN]\${NC} \$1"
}

log_error() {
  echo -e "\${RED}[ERROR]\${NC} \$1"
}

# Bootstrap: Install dependencies
bootstrap() {
  log_info "Installing dependencies..."
  # TODO: Add your install command
  echo "Please configure install command in this script"
}

# Dev: Start development environment
dev() {
  log_info "Starting development server..."
  # TODO: Add your dev command
  echo "Please configure dev command in this script"
}

# Check: Run tests and basic validation
check() {
  log_info "Running tests..."
  # TODO: Add your test command
  echo "Please configure test command in this script"
}

# Verify: Run all available verification checks
verify() {
  local exit_code=0

  log_info "Running verification checks..."

  # Run type check if TypeScript detected
  if [ -f "tsconfig.json" ]; then
    log_info "Running type check..."
    if ! npx tsc --noEmit; then
      log_error "Type check failed"
      exit_code=1
    fi
  fi

  log_warn "Configure test/lint/build commands for full verification"

  if [ \$exit_code -eq 0 ]; then
    log_info "Verification checks passed!"
  else
    log_error "Some verification checks failed"
  fi

  return \$exit_code
}

# Build: Build for production
build() {
  log_info "Building for production..."
  # TODO: Add your build command
  echo "Please configure build command in this script"
}

# Status: Show project status
status() {
  log_info "Project Status"
  echo "---"

  if [ -f "ai/feature_list.json" ]; then
    echo "Feature List: ai/feature_list.json"
    if command -v jq &> /dev/null; then
      local total=$(jq '.features | length' ai/feature_list.json)
      local passing=$(jq '[.features[] | select(.status == "passing")] | length' ai/feature_list.json)
      echo "  Total: \$total"
      echo "  Passing: \$passing"
    fi
  else
    log_warn "No feature list found. Run 'agent-foreman init' first."
  fi
}

# Help
show_help() {
  echo "Usage: ./ai/init.sh <command>"
  echo ""
  echo "Commands:"
  echo "  bootstrap  Install dependencies"
  echo "  dev        Start development server"
  echo "  check      Run tests and validation"
  echo "  verify     Run all verification checks (tests, types, lint, build)"
  echo "  build      Build for production"
  echo "  status     Show project status"
  echo "  help       Show this help message"
}

# Main entry point
case "\${1:-help}" in
  bootstrap)
    bootstrap
    ;;
  dev)
    dev
    ;;
  check)
    check
    ;;
  verify)
    verify
    ;;
  build)
    build
    ;;
  status)
    status
    ;;
  help|--help|-h)
    show_help
    ;;
  *)
    log_error "Unknown command: \$1"
    show_help
    exit 1
    ;;
esac
`;
}
