/**
 * Prompt templates for CLAUDE.md and other documentation
 */

/**
 * Generate the Long-Task Harness section content
 */
export function generateHarnessSection(goal: string): string {
  return `## Long-Task Harness

This project uses the **agent-foreman** harness for feature-driven development with AI agents.

### Project Goal

${goal}

### Core Files

| File | Purpose |
|------|---------|
| \`ai/feature_list.json\` | Feature backlog with status tracking |
| \`ai/progress.md\` | Session handoff audit log |
| \`ai/init.sh\` | Bootstrap script (install/dev/check) |

### Feature Status Values

- \`failing\` - Not yet implemented or incomplete
- \`passing\` - Acceptance criteria met
- \`blocked\` - External dependency blocking
- \`needs_review\` - Potentially affected by recent changes
- \`deprecated\` - No longer needed

### Workflow for Each Session

1. **Start** - Read \`ai/feature_list.json\` and recent \`ai/progress.md\`
2. **Select** - Pick the highest priority feature (\`needs_review\` > \`failing\`)
3. **Plan** - Review acceptance criteria before coding
4. **Implement** - Work on ONE feature at a time
5. **Test** - Run \`./ai/init.sh check\` to verify
6. **Complete** - Run \`agent-foreman complete <feature_id>\` (auto-verifies + commits)
7. **Log** - Entry automatically added to progress log
8. **Next** - Move to next feature or celebrate completion

### Rules

1. **One feature per session** - Complete or pause cleanly before switching
2. **Don't modify acceptance criteria** - Only change \`status\` and \`notes\`
3. **Update status promptly** - Mark features passing when criteria met
4. **Leave clean state** - No broken code between sessions
5. **Use single-line log format** - One line per entry, not verbose Markdown

### Progress Log Format

Append entries to \`ai/progress.md\` using this **single-line format only**:

\`\`\`
STEP 2025-01-15T10:30:00Z feature=auth.login status=passing summary="Implemented login flow"
CHANGE 2025-01-15T11:00:00Z feature=auth.login action=refactor reason="Improved error handling"
REPLAN 2025-01-15T12:00:00Z summary="Splitting auth into submodules" note="Original scope too large"
\`\`\`

**Log types**: \`INIT\` | \`STEP\` | \`CHANGE\` | \`REPLAN\` | \`VERIFY\`

**IMPORTANT**: Do NOT write verbose Markdown session notes. Keep each entry as a single line.

### Commands

\`\`\`bash
# View project status
agent-foreman status

# Work on next priority feature
agent-foreman step

# Work on specific feature
agent-foreman step <feature_id>

# Verify and mark feature as complete (AI verification + auto-commit)
agent-foreman complete <feature_id>

# Skip verification (not recommended)
agent-foreman complete <feature_id> --skip-verify

# Preview verification without completing
agent-foreman verify <feature_id>

# Analyze impact of changes
agent-foreman impact <feature_id>

# Bootstrap/development/testing
./ai/init.sh bootstrap
./ai/init.sh dev
./ai/init.sh check
\`\`\`

### Feature ID Convention

Feature IDs use dot notation: \`module.submodule.action\`

Examples:
- \`auth.login\`
- \`chat.message.edit\`
- \`api.users.create\`

### Acceptance Criteria Format

Write criteria as testable statements:
- "User can submit the form and see a success message"
- "API returns 201 status with created resource"
- "Error message displays when validation fails"

### Feature JSON Schema

**IMPORTANT**: When adding or modifying features in \`ai/feature_list.json\`, use this exact schema:

\`\`\`json
{
  "features": [
    {
      "id": "module.feature.action",
      "description": "Human-readable description of the feature",
      "module": "parent-module-name",
      "priority": 1,
      "status": "failing",
      "acceptance": [
        "First acceptance criterion",
        "Second acceptance criterion"
      ],
      "dependsOn": ["other.feature.id"],
      "supersedes": [],
      "tags": ["optional-tag"],
      "version": 1,
      "origin": "manual",
      "notes": ""
    }
  ],
  "metadata": {
    "projectGoal": "Project goal description",
    "createdAt": "2024-01-01T00:00:00.000Z",
    "updatedAt": "2024-01-01T00:00:00.000Z",
    "version": "1.0.0"
  }
}
\`\`\`

**Required fields**: \`id\`, \`description\`, \`module\`, \`priority\`, \`status\`, \`acceptance\`, \`version\`, \`origin\`

**Status values**: \`failing\` | \`passing\` | \`blocked\` | \`needs_review\` | \`deprecated\`

**Origin values**: \`init-auto\` | \`init-from-routes\` | \`init-from-tests\` | \`manual\` | \`replan\`

---

*Generated by agent-foreman - https://github.com/mylukin/agent-foreman*`;
}

/**
 * Generate CLAUDE.md content for a project (new file)
 */
export function generateClaudeMd(goal: string): string {
  return `# Project Instructions

${generateHarnessSection(goal)}
`;
}

/**
 * Generate a commit message template
 */
export function generateCommitMessage(
  featureId: string,
  description: string,
  summary: string
): string {
  return `feat(${featureId.split(".")[0]}): ${description}

${summary}

Feature: ${featureId}

🤖 Generated with agent-foreman`;
}

/**
 * Generate feature step guidance
 */
export function generateFeatureGuidance(feature: {
  id: string;
  description: string;
  acceptance: string[];
  dependsOn: string[];
  notes: string;
}): string {
  const lines: string[] = [];

  lines.push(`## Feature: ${feature.id}`);
  lines.push("");
  lines.push(`**Description:** ${feature.description}`);
  lines.push("");
  lines.push("### Acceptance Criteria");
  lines.push("");
  for (const [i, criteria] of feature.acceptance.entries()) {
    lines.push(`${i + 1}. [ ] ${criteria}`);
  }

  if (feature.dependsOn.length > 0) {
    lines.push("");
    lines.push("### Dependencies");
    lines.push("");
    lines.push("Ensure these features are passing first:");
    for (const dep of feature.dependsOn) {
      lines.push(`- ${dep}`);
    }
  }

  if (feature.notes) {
    lines.push("");
    lines.push("### Notes");
    lines.push("");
    lines.push(feature.notes);
  }

  lines.push("");
  lines.push("### Workflow");
  lines.push("");
  lines.push("1. Review acceptance criteria above");
  lines.push("2. Implement the feature");
  lines.push("3. Run `./ai/init.sh check` to verify");
  lines.push("4. Run `agent-foreman complete ${feature.id}` (auto-verifies + commits)");

  return lines.join("\n");
}

/**
 * Generate impact review guidance
 */
export function generateImpactGuidance(
  changedFeature: string,
  affectedFeatures: { id: string; reason: string }[]
): string {
  const lines: string[] = [];

  lines.push(`## Impact Review: ${changedFeature}`);
  lines.push("");

  if (affectedFeatures.length === 0) {
    lines.push("No other features are affected by this change.");
    return lines.join("\n");
  }

  lines.push("The following features may be affected by this change:");
  lines.push("");
  lines.push("| Feature | Reason | Action |");
  lines.push("|---------|--------|--------|");

  for (const f of affectedFeatures) {
    lines.push(`| ${f.id} | ${f.reason} | Review and update status |`);
  }

  lines.push("");
  lines.push("### Recommended Actions");
  lines.push("");
  lines.push("1. Review each affected feature");
  lines.push("2. Run tests for affected modules");
  lines.push("3. Mark as `needs_review` if uncertain");
  lines.push("4. Update `notes` field with impact details");

  return lines.join("\n");
}

/**
 * Generate session summary
 */
export function generateSessionSummary(
  completed: { id: string; description: string }[],
  remaining: { id: string; priority: number }[],
  nextFeature: { id: string; description: string } | null
): string {
  const lines: string[] = [];

  lines.push("## Session Summary");
  lines.push("");

  if (completed.length > 0) {
    lines.push("### Completed This Session");
    for (const f of completed) {
      lines.push(`- ✅ ${f.id}: ${f.description}`);
    }
    lines.push("");
  }

  lines.push(`### Remaining: ${remaining.length} features`);
  lines.push("");

  if (nextFeature) {
    lines.push("### Next Up");
    lines.push(`**${nextFeature.id}**: ${nextFeature.description}`);
  } else {
    lines.push("🎉 All features are complete!");
  }

  return lines.join("\n");
}
