/**
 * Prompt templates for CLAUDE.md and other documentation
 */

/**
 * Generate CLAUDE.md content for a project
 */
export function generateClaudeMd(goal: string): string {
  return `# Project Instructions

## Project Goal

${goal}

## Long-Task Harness

This project uses the **agent-foreman** harness for feature-driven development with AI agents.

### Core Files

| File | Purpose |
|------|---------|
| \`ai/feature_list.json\` | Feature backlog with status tracking |
| \`ai/progress.md\` | Session handoff audit log |
| \`ai/init.sh\` | Bootstrap script (install/dev/check) |

### Feature Status Values

- \`failing\` - Not yet implemented or incomplete
- \`passing\` - Acceptance criteria met
- \`blocked\` - External dependency blocking
- \`needs_review\` - Potentially affected by recent changes
- \`deprecated\` - No longer needed

### Workflow for Each Session

1. **Start** - Read \`ai/feature_list.json\` and recent \`ai/progress.md\`
2. **Select** - Pick the highest priority feature (\`needs_review\` > \`failing\`)
3. **Plan** - Review acceptance criteria before coding
4. **Implement** - Work on ONE feature at a time
5. **Test** - Run \`./ai/init.sh check\` to verify
6. **Update** - Mark feature as \`passing\` if criteria met
7. **Log** - Entry automatically added to progress log
8. **Commit** - Create clean commit with feature ID

### Rules

1. **One feature per session** - Complete or pause cleanly before switching
2. **Don't modify acceptance criteria** - Only change \`status\` and \`notes\`
3. **Update status promptly** - Mark features passing when criteria met
4. **Leave clean state** - No broken code between sessions
5. **Log everything** - Progress log is your handoff mechanism

### Commands

\`\`\`bash
# View project status
agent-foreman status

# Work on next priority feature
agent-foreman step

# Work on specific feature
agent-foreman step <feature_id>

# Analyze impact of changes
agent-foreman impact <feature_id>

# Bootstrap/development/testing
./ai/init.sh bootstrap
./ai/init.sh dev
./ai/init.sh check
\`\`\`

### Feature ID Convention

Feature IDs use dot notation: \`module.submodule.action\`

Examples:
- \`auth.login\`
- \`chat.message.edit\`
- \`api.users.create\`

### Acceptance Criteria Format

Write criteria as testable statements:
- "User can submit the form and see a success message"
- "API returns 201 status with created resource"
- "Error message displays when validation fails"

---

*Generated by agent-foreman - https://github.com/mylukin/agent-foreman*
`;
}

/**
 * Generate a commit message template
 */
export function generateCommitMessage(
  featureId: string,
  description: string,
  summary: string
): string {
  return `feat(${featureId.split(".")[0]}): ${description}

${summary}

Feature: ${featureId}

🤖 Generated with agent-foreman`;
}

/**
 * Generate feature step guidance
 */
export function generateFeatureGuidance(feature: {
  id: string;
  description: string;
  acceptance: string[];
  dependsOn: string[];
  notes: string;
}): string {
  const lines: string[] = [];

  lines.push(`## Feature: ${feature.id}`);
  lines.push("");
  lines.push(`**Description:** ${feature.description}`);
  lines.push("");
  lines.push("### Acceptance Criteria");
  lines.push("");
  for (const [i, criteria] of feature.acceptance.entries()) {
    lines.push(`${i + 1}. [ ] ${criteria}`);
  }

  if (feature.dependsOn.length > 0) {
    lines.push("");
    lines.push("### Dependencies");
    lines.push("");
    lines.push("Ensure these features are passing first:");
    for (const dep of feature.dependsOn) {
      lines.push(`- ${dep}`);
    }
  }

  if (feature.notes) {
    lines.push("");
    lines.push("### Notes");
    lines.push("");
    lines.push(feature.notes);
  }

  lines.push("");
  lines.push("### Workflow");
  lines.push("");
  lines.push("1. Review acceptance criteria above");
  lines.push("2. Implement the feature");
  lines.push("3. Run `./ai/init.sh check` to verify");
  lines.push("4. Update feature status to `passing` if all criteria met");
  lines.push("5. Commit with message: `feat(${feature.id.split('.')[0]}): ${feature.description}`");

  return lines.join("\n");
}

/**
 * Generate impact review guidance
 */
export function generateImpactGuidance(
  changedFeature: string,
  affectedFeatures: { id: string; reason: string }[]
): string {
  const lines: string[] = [];

  lines.push(`## Impact Review: ${changedFeature}`);
  lines.push("");

  if (affectedFeatures.length === 0) {
    lines.push("No other features are affected by this change.");
    return lines.join("\n");
  }

  lines.push("The following features may be affected by this change:");
  lines.push("");
  lines.push("| Feature | Reason | Action |");
  lines.push("|---------|--------|--------|");

  for (const f of affectedFeatures) {
    lines.push(`| ${f.id} | ${f.reason} | Review and update status |`);
  }

  lines.push("");
  lines.push("### Recommended Actions");
  lines.push("");
  lines.push("1. Review each affected feature");
  lines.push("2. Run tests for affected modules");
  lines.push("3. Mark as `needs_review` if uncertain");
  lines.push("4. Update `notes` field with impact details");

  return lines.join("\n");
}

/**
 * Generate session summary
 */
export function generateSessionSummary(
  completed: { id: string; description: string }[],
  remaining: { id: string; priority: number }[],
  nextFeature: { id: string; description: string } | null
): string {
  const lines: string[] = [];

  lines.push("## Session Summary");
  lines.push("");

  if (completed.length > 0) {
    lines.push("### Completed This Session");
    for (const f of completed) {
      lines.push(`- ✅ ${f.id}: ${f.description}`);
    }
    lines.push("");
  }

  lines.push(`### Remaining: ${remaining.length} features`);
  lines.push("");

  if (nextFeature) {
    lines.push("### Next Up");
    lines.push(`**${nextFeature.id}**: ${nextFeature.description}`);
  } else {
    lines.push("🎉 All features are complete!");
  }

  return lines.join("\n");
}
