/**
 * Implementation of `run` command
 * Executes JSON step files generated by `analyze` command
 */
import * as fs from "node:fs/promises";
import * as path from "node:path";
import { spawnSync } from "node:child_process";
import chalk from "chalk";
import { callAnyAvailableAgent } from "./agents.js";
import { extractJsonObject, type VerificationItem } from "./analyze.js";

export type StepStatus = "🔴 待完成" | "🟡 进行中" | "🟢 已完成";

export interface StepUnitTest {
  command: string;
  files?: string[];
  notes?: string;
}

export interface StepJson {
  id: string;
  description: string;
  status: StepStatus;
  verification: VerificationItem[];
  unit_test?: StepUnitTest;
  // Allow extra fields for forward compatibility
  [key: string]: unknown;
}

export interface PreviousAttemptFailureContext {
  attempt: number;
  maxAttempts: number;
  fromStatus: StepStatus;
  toStatus: StepStatus;
  unitTestCommand?: string;
  unitTestOutputSnippet?: string;
  verificationError?: string;
  aiError?: string;
}

export interface RunStepsOptions {
  fullVerify?: boolean;
  verifyOnly?: boolean;
  verifyUnitTestOnly?: boolean;
  verifyGenerateUnitTest?: boolean;
}

interface RunStepEntry {
  order: number;
  prefix: string;
  fileName: string;
  filePath: string;
  id?: string;
  description?: string;
  initialStatus?: StepStatus;
  finalStatus?: StepStatus;
  verification?: VerificationItem[];
  unitTest?: StepUnitTest;
  parseError?: string;
  success?: boolean;
  error?: string;
}

function isStepJson(value: unknown): value is StepJson {
  if (!value || typeof value !== "object") {
    return false;
  }

  const obj = value as { [key: string]: unknown };

  if (typeof obj.id !== "string" || !obj.id.trim()) {
    return false;
  }

  if (typeof obj.description !== "string" || !obj.description.trim()) {
    return false;
  }

  if (typeof obj.status !== "string") {
    return false;
  }

  const allowedStatuses: StepStatus[] = ["🔴 待完成", "🟡 进行中", "🟢 已完成"];
  if (!allowedStatuses.includes(obj.status as StepStatus)) {
    return false;
  }

  if (!Array.isArray(obj.verification)) {
    return false;
  }

  for (const [index, item] of obj.verification.entries()) {
    if (!item || typeof item !== "object") {
      return false;
    }
    const v = item as { type?: unknown; description?: unknown };
    if (typeof v.type !== "string" || !v.type.trim()) {
      return false;
    }
    if (typeof v.description !== "string" || !v.description.trim()) {
      return false;
    }
    // If any verification entry is invalid, consider structure invalid
    if (v.type.trim().length === 0 || v.description.trim().length === 0) {
      throw new Error(`verification[${index}] has empty type or description`);
    }
  }

  return true;
}

function truncateDescription(description: string, maxLength = 120): string {
  const trimmed = description.trim();
  if (trimmed.length <= maxLength) {
    return trimmed;
  }
  return `${trimmed.slice(0, maxLength - 1)}…`;
}

function formatDateTime(dt: Date): string {
  const year = dt.getFullYear();
  const month = String(dt.getMonth() + 1).padStart(2, "0");
  const day = String(dt.getDate()).padStart(2, "0");
  const hour = String(dt.getHours()).padStart(2, "0");
  const minute = String(dt.getMinutes()).padStart(2, "0");
  const second = String(dt.getSeconds()).padStart(2, "0");
  return `${year}-${month}-${day} ${hour}:${minute}:${second}`;
}

function buildOutputSnippet(
  output: string,
  maxLines = 20,
  maxLength = 2000,
): string {
  const lines = output.split("\n");
  const sliced = lines.slice(0, maxLines);
  let snippet = sliced.join("\n");

  if (snippet.length > maxLength) {
    snippet = `${snippet.slice(0, maxLength - 1)}…`;
  }

  if (lines.length > maxLines) {
    snippet = `${snippet}\n... (output truncated)`;
  }

  return snippet.trim();
}

function buildRunStepPrompt(params: {
  projectRoot: string;
  stepsDir: string;
  step: StepJson;
  fileName: string;
  order: number;
  total: number;
}): string {
  const { projectRoot, stepsDir, step, fileName, order, total } = params;

  const verificationLines =
    step.verification.length > 0
      ? step.verification
          .map(
            (v, index) =>
              `${index + 1}. [${v.type}] ${v.description}`,
          )
          .join("\n")
      : "（当前步骤没有显式的 verification 条目，但你仍需要根据描述编写合理的测试或验证方式。）";

  return `你是 agent-foreman 工程中的下游 AI 工具，负责在本地代码仓库中实现具体的开发步骤。

当前项目根目录（工作目录）为：
${projectRoot}

步骤文件所在目录为：
${stepsDir}

本次要执行的步骤信息如下：
- 顺序：第 ${order} 步 / 共 ${total} 步
- 步骤文件：${fileName}
- 步骤 ID：${step.id}
- 描述（description）：
${step.description}

验证项目（verification）列表如下，请务必全部覆盖：
${verificationLines}

你的任务：
1. 在项目代码仓库中，根据上述步骤描述完成对应的实现工作（包括代码修改、配置调整、文档更新等）。
2. 针对每一个 verification 条目，编写并运行相应的自动化测试或验证步骤：
   - type 为 "unit" 时：编写或更新单元测试并运行；
   - type 为 "integration" 时：编写或更新集成测试并运行；
   - type 为 "ui" 时：编写或更新 UI 自动化测试并运行；
   - type 为 "manual" 或其他类型时：给出清晰的人工验证说明，必要时也可以补充自动化测试。
3. 充分利用你在本地可用的命令（例如 npm、pnpm、yarn、pytest、go test 等）运行测试，确保相关测试全部通过。
4. 遵循本仓库已有的代码风格和项目结构，尽量保持改动最小且聚焦当前步骤。
5. 在完成实现和单元测试编写后，请根据你实际使用的测试命令，在输出末尾附加一个仅包含 \`unit_test\` 字段的 JSON 对象，用于记录如何重新运行与本步骤相关的单元测试。格式示例：

{
  "unit_test": {
    "command": "npm test -- tests/run-command.test.ts",
    "files": ["tests/run-command.test.ts"],
    "notes": "覆盖 runStepsDirectory 的主要场景"
  }
}

要求：
- 只输出上述 JSON 对象，不要使用 Markdown 代码块；
- JSON 中必须使用英文双引号；
- 如果你认为本步骤不需要或无法编写专门的单元测试，可以省略 \`unit_test\` 字段（不要输出空字段）。

退出约定：
- 当且仅当你认为当前步骤已经完全实现，且所有相关测试均通过时，才以退出码 0 正常结束；
- 如果你无法完成当前步骤、遇到无法解决的错误、或有任何测试失败，请以非 0 退出码结束，并在输出中简要说明原因。

请现在开始执行该步骤。`;
}

export function appendPreviousFailureContextToPrompt(params: {
  basePrompt: string;
  context?: PreviousAttemptFailureContext;
}): string {
  const { basePrompt, context } = params;
  if (!context) {
    return basePrompt;
  }

  const lines: string[] = [];
  lines.push("");
  lines.push("====== 上一轮尝试失败原因摘要 ======");
  lines.push("");
  lines.push(
    `- 上一轮尝试序号：第 ${context.attempt}/${context.maxAttempts} 轮`,
  );
  lines.push(
    `- 上一轮步骤状态变化：${context.fromStatus} → ${context.toStatus}`,
  );

  if (context.unitTestCommand) {
    lines.push(
      `- 最近一次单元测试命令：${context.unitTestCommand}`,
    );
    if (context.unitTestOutputSnippet) {
      lines.push("- 单元测试关键输出（已截断）：");
      lines.push(context.unitTestOutputSnippet);
    }
  }

  if (context.verificationError) {
    lines.push(
      `- verification 阶段的错误信息：${context.verificationError}`,
    );
  }

  if (context.aiError) {
    lines.push(`- AI 实现阶段返回的错误：${context.aiError}`);
  }

  lines.push("");
  lines.push(
    "请在本轮实现中重点根据上述失败原因进行有针对性的修复。",
  );

  return `${basePrompt}\n\n${lines.join("\n")}`;
}

function logAttemptFailureSummary(context: PreviousAttemptFailureContext): void {
  const base = `  ℹ 本轮失败摘要：第 ${context.attempt}/${context.maxAttempts} 轮，步骤状态 ${context.fromStatus} → ${context.toStatus}`;

  if (context.unitTestCommand) {
    console.log(
      chalk.yellow(
        `${base}，最近一次单元测试命令 "${context.unitTestCommand}" 失败`,
      ),
    );
    return;
  }

  if (context.verificationError) {
    console.log(
      chalk.yellow(
        `${base}，verification 验证失败：${context.verificationError}`,
      ),
    );
    return;
  }

  if (context.aiError) {
    console.log(
      chalk.yellow(
        `${base}，AI 实现阶段返回错误：${context.aiError}`,
      ),
    );
    return;
  }

  console.log(chalk.yellow(base));
}

function buildRunStepValidationPrompt(params: {
  projectRoot: string;
  stepsDir: string;
  step: StepJson;
  fileName: string;
  order: number;
  total: number;
}): string {
  const { projectRoot, stepsDir, step, fileName, order, total } = params;

  const verificationLines =
    step.verification.length > 0
      ? step.verification
          .map(
            (v, index) =>
              `${index + 1}. [${v.type}] ${v.description}`,
          )
          .join("\n")
      : "（当前步骤没有显式的 verification 条目，但你仍需要根据描述选择合理的测试或验证方式。）";

  return `你是 agent-foreman 工程中的测试验证助手，负责在本地代码仓库中根据步骤描述和 verification 列表重新运行测试，进行回归验证。

当前项目根目录（工作目录）为：
${projectRoot}

步骤文件所在目录为：
${stepsDir}

本次要验证的步骤信息如下：
- 顺序：第 ${order} 步 / 共 ${total} 步
- 步骤文件：${fileName}
- 步骤 ID：${step.id}
- 当前步骤在 JSON 中的状态：${step.status}
- 描述（description）：
${step.description}

验证项目（verification）列表如下，请务必全部覆盖：
${verificationLines}

你的任务（仅限测试验证，不允许修改任何代码或配置）：
1. 只根据上述描述和 verification 条目，选择并执行合适的测试命令（例如 npm test / pnpm test / 自定义脚本等），验证该步骤对应的功能是否仍然正确。
2. 你可以阅读代码和测试文件，但禁止修改任何源代码、配置文件、测试文件或文档内容——本轮仅做「回归验证」，不做实现改动。
3. 如果你认为所有与本步骤相关的测试均已覆盖且全部通过，则以退出码 0 正常结束。
4. 如果有任意测试失败、发现明显缺陷、或你无法确认该步骤已经完全满足描述和 verification 要求，请以非 0 退出码结束，并在输出中简要说明失败原因或风险点。

退出约定：
- 退出码 0：表示本次回归验证通过，当前步骤可以继续保持为“🟢 已完成”状态；
- 非 0 退出码：表示本次回归验证未通过或存在不确定性，调用方会根据需要重新打开步骤并进入实现阶段。

请现在开始执行回归验证，仅运行测试和检查结果，不要修改任何代码或配置。`;
}

async function discoverStepFiles(stepsDir: string): Promise<{
  stepFiles: string[];
  otherJsonFiles: string[];
}> {
  const entries = await fs.readdir(stepsDir);
  const jsonFiles = entries.filter((name) => name.toLowerCase().endsWith(".json"));

  if (jsonFiles.length === 0) {
    throw new Error("步骤目录中未找到任何 JSON 步骤文件");
  }

  const stepPattern = /^\d{3}-.+\.json$/;
  const stepFiles = jsonFiles.filter((name) => stepPattern.test(name));
  const otherJsonFiles = jsonFiles.filter((name) => !stepPattern.test(name));

  if (stepFiles.length === 0) {
    throw new Error(
      `在步骤目录中未找到符合 "NNN-*.json" 命名规则的步骤文件，找到的 JSON 文件有：${jsonFiles.join(
        ", ",
      )}`,
    );
  }

  stepFiles.sort((a, b) => a.localeCompare(b));

  return { stepFiles, otherJsonFiles };
}

export async function loadStepEntries(
  stepsDir: string,
  stepFiles: string[],
): Promise<{ entries: RunStepEntry[]; hasParseError: boolean }> {
  const entries: RunStepEntry[] = [];
  let hasParseError = false;

  for (let index = 0; index < stepFiles.length; index++) {
    const fileName = stepFiles[index];
    const filePath = path.join(stepsDir, fileName);
    const prefix = fileName.slice(0, 3);
    const order = index + 1;
    const entry: RunStepEntry = {
      order,
      prefix,
      fileName,
      filePath,
    };

    try {
      const content = await fs.readFile(filePath, "utf-8");
      let parsed: unknown;
      try {
        parsed = JSON.parse(content);
      } catch (err) {
        throw new Error(
          err instanceof Error ? `JSON 解析失败：${err.message}` : "JSON 解析失败",
        );
      }

      if (!isStepJson(parsed)) {
        throw new Error("JSON 结构不符合步骤文件要求");
      }

      const step = parsed as StepJson;

      entry.id = step.id;
      entry.description = step.description;
      entry.initialStatus = step.status;
      entry.finalStatus = step.status;
      entry.verification = step.verification;
      entry.unitTest = step.unit_test;

      const expectedId = `step-${prefix}`;
      if (step.id !== expectedId) {
        console.log(
          chalk.yellow(
            `⚠ 步骤文件 ${fileName} 的 id 字段为 "${step.id}"，与文件名前缀 "${prefix}" 不一致（预期为 "${expectedId}"）`,
          ),
        );
      }
    } catch (err) {
      hasParseError = true;
      const message =
        err instanceof Error ? err.message : "未知错误，无法解析步骤 JSON 文件";
      entry.parseError = message;
      entry.error = message;
      console.log(
        chalk.red(
          `✗ 无法解析步骤文件 ${fileName}: ${message}`,
        ),
      );
    }

    entries.push(entry);
  }

  return { entries, hasParseError };
}

export async function writeProgressMarkdown(params: {
  stepsDir: string;
  entries: RunStepEntry[];
  startedAt: Date;
  finishedAt: Date;
}): Promise<string> {
  const { stepsDir, entries, startedAt, finishedAt } = params;

  const fileName = "run-progress.md";
  const filePath = path.join(stepsDir, fileName);

  const total = entries.length;
  const successCount = entries.filter((e) => e.success).length;
  const failureCount = entries.filter((e) => e.success === false).length;

  const lines: string[] = [];

  lines.push(`# agent-foreman run 执行进度报告`);
  lines.push("");
  lines.push(`- 步骤目录: \`${stepsDir}\``);
  lines.push(`- 开始时间: ${formatDateTime(startedAt)}`);
  lines.push(`- 结束时间: ${formatDateTime(finishedAt)}`);
  lines.push(`- 总步骤数: ${total}`);
  lines.push(`- 成功步骤数: ${successCount}`);
  lines.push(`- 失败步骤数: ${failureCount}`);
  lines.push("");

  lines.push("## 步骤明细");
  lines.push("");
  lines.push("| 顺序 | 文件名 | 步骤 ID | 执行前状态 | 执行后状态 | 结果 | 摘要 | 错误信息 |");
  lines.push("| ---- | ------ | ------- | ---------- | ---------- | ---- | ---- | -------- |");

  for (const entry of entries) {
    const before = entry.initialStatus ?? "";
    const after = entry.finalStatus ?? before;
    const result =
      entry.success === true
        ? "成功"
        : entry.success === false
          ? "失败"
          : "未执行";
    const summary = entry.description
      ? truncateDescription(entry.description, 60).replace(/\|/g, "\\|")
      : "";
    const error = entry.error
      ? truncateDescription(entry.error, 80).replace(/\|/g, "\\|")
      : "";

    lines.push(
      `| ${entry.order
        .toString()
        .padStart(3, " ")} | ${entry.fileName} | ${entry.id ?? ""} | ${before} | ${after} | ${result} | ${summary} | ${error} |`,
    );
  }

  const content = `${lines.join("\n")}\n`;
  await fs.writeFile(filePath, content, "utf-8");

  return filePath;
}

export function extractUnitTestFromOutput(output: string): StepUnitTest | undefined {
  const jsonStr = extractJsonObject(output);
  if (!jsonStr) return undefined;

  let parsed: unknown;
  try {
    parsed = JSON.parse(jsonStr);
  } catch {
    return undefined;
  }

  if (!parsed || typeof parsed !== "object") return undefined;

  const obj = parsed as { unit_test?: unknown };
  const rawUnit = obj.unit_test;
  if (!rawUnit || typeof rawUnit !== "object") return undefined;

  const u = rawUnit as { command?: unknown; files?: unknown; notes?: unknown };

  if (typeof u.command !== "string" || !u.command.trim()) return undefined;
  const command = u.command.trim();

  let files: string[] | undefined;
  if (Array.isArray(u.files)) {
    files = u.files.filter((f): f is string => typeof f === "string" && f.trim().length > 0);
  }

  const notes = typeof u.notes === "string" && u.notes.trim().length > 0 ? u.notes.trim() : undefined;

  return { command, files, notes };
}

async function runUnitTestsForStep(
  unitTest: StepUnitTest,
  cwd: string,
): Promise<{ success: boolean; error?: string; output?: string }> {
  const result = spawnSync(unitTest.command, {
    cwd,
    shell: true,
    encoding: "utf-8",
  });

  const stdout = (result.stdout || "").toString();
  const stderr = (result.stderr || "").toString();
  const combined = `${stdout}${stdout && stderr ? "\n" : ""}${stderr}`;

  if (result.status === 0) {
    return { success: true, output: combined };
  }

  const message =
    combined.trim() || `Unit test command exited with code ${result.status ?? "unknown"}`;

  return {
    success: false,
    error: message,
    output: combined,
  };
}

const MAX_ATTEMPTS = 5;

export async function runStepsDirectory(
  stepsDirArg: string,
  options: RunStepsOptions = {},
): Promise<void> {
  const cwd = process.cwd();
  const stepsDir = path.isAbsolute(stepsDirArg)
    ? stepsDirArg
    : path.join(cwd, stepsDirArg);

  const startedAt = new Date();

  let stat;
  try {
    stat = await fs.stat(stepsDir);
  } catch {
    console.log(chalk.red(`✗ 步骤目录不存在：${stepsDirArg}`));
    process.exitCode = 1;
    return;
  }

  if (!stat.isDirectory()) {
    console.log(chalk.red(`✗ 提供的路径不是目录：${stepsDirArg}`));
    process.exitCode = 1;
    return;
  }

  let stepFiles: string[];
  let otherJsonFiles: string[];

  try {
    const discovered = await discoverStepFiles(stepsDir);
    stepFiles = discovered.stepFiles;
    otherJsonFiles = discovered.otherJsonFiles;
  } catch (err) {
    const message =
      err instanceof Error ? err.message : "无法发现步骤 JSON 文件";
    console.log(chalk.red(`✗ ${message}`));
    process.exitCode = 1;
    return;
  }

  if (otherJsonFiles.length > 0) {
    console.log(
      chalk.yellow(
        `⚠ 发现 ${otherJsonFiles.length} 个命名不符合 "NNN-*.json" 规则的 JSON 文件，它们不会作为步骤执行：${otherJsonFiles.join(
          ", ",
        )}`,
      ),
    );
  }

  console.log(
    chalk.blue(
      `🧩 即将执行 ${stepFiles.length} 个步骤（目录：${stepsDirArg}）`,
    ),
  );
  console.log(
    chalk.gray(
      `  执行顺序（前几项预览）：${stepFiles
        .slice(0, 5)
        .join(", ")}${stepFiles.length > 5 ? " ..." : ""}`,
    ),
  );

  const { entries, hasParseError } = await loadStepEntries(stepsDir, stepFiles);

  if (hasParseError) {
    console.log(
      chalk.red(
        "✗ 有步骤 JSON 文件结构不合法，已中止执行。请修正上述错误后重试。",
      ),
    );
    const finishedAt = new Date();
    const progressPath = await writeProgressMarkdown({
      stepsDir,
      entries,
      startedAt,
      finishedAt,
    });
    console.log(chalk.gray(`  执行进度报告已写入：${progressPath}`));
    process.exitCode = 1;
    return;
  }

  const verifyOnly = options.verifyOnly === true;
  const verifyUnitTestOnly = options.verifyUnitTestOnly === true;
  const verifyGenerateUnitTest = options.verifyGenerateUnitTest === true;
  const fullVerify = options.fullVerify === true;

  const enabledModesCount = [
    verifyOnly,
    verifyUnitTestOnly,
    verifyGenerateUnitTest,
    fullVerify,
  ].filter(Boolean).length;

  if (enabledModesCount > 1) {
    console.log(
      chalk.red(
        "✗ runStepsDirectory 选项冲突：fullVerify、verifyOnly、verifyUnitTestOnly、verifyGenerateUnitTest 不能同时启用多个。",
      ),
    );
    process.exitCode = 1;
    return;
  }

  const mode: "normal" | "full-verify" | "verify-only" | "verify-unit-test-only" | "verify-generate-unit-test" =
    verifyOnly
      ? "verify-only"
      : verifyUnitTestOnly
        ? "verify-unit-test-only"
        : verifyGenerateUnitTest
          ? "verify-generate-unit-test"
          : fullVerify
            ? "full-verify"
            : "normal";

  const total = entries.length;
  let firstFailure: RunStepEntry | undefined;

  for (const entry of entries) {
    if (!entry.id || !entry.description || !entry.verification) {
      // Should not happen if loadStepEntries passed validation, but keep safe
      entry.success = false;
      entry.error = "步骤元数据不完整，无法执行";
      firstFailure = firstFailure ?? entry;
      break;
    }

    const step: StepJson = {
      id: entry.id,
      description: entry.description,
      status: entry.initialStatus ?? "🔴 待完成",
      verification: entry.verification,
    };
    if (entry.unitTest) {
      step.unit_test = entry.unitTest;
    }

    console.log("");
    console.log(
      chalk.bold(
        `[${entry.order}/${total}] ${entry.fileName} (${step.id})`,
      ),
    );
    console.log(
      chalk.gray(
        `  描述: ${truncateDescription(step.description)}`,
      ),
    );
    console.log(
      chalk.gray(
        `  当前状态: ${step.status}`,
      ),
    );

    if (mode === "verify-generate-unit-test") {
      console.log(
        chalk.gray(
          "  当前运行模式：仅检查并为缺少配置的步骤生成 unit_test。",
        ),
      );

      if (entry.unitTest && entry.unitTest.command) {
        console.log(
          chalk.gray(
            `  已存在 unit_test 配置，命令：${entry.unitTest.command}，跳过生成。`,
          ),
        );
        entry.finalStatus = step.status;
        entry.success = true;
        entry.error = undefined;
        continue;
      }

      console.log(
        chalk.gray(
          "  当前步骤尚未配置 unit_test，将尝试调用命令行 AI 生成单元测试并写入步骤 JSON...",
        ),
      );

      const basePrompt = buildRunStepPrompt({
        projectRoot: cwd,
        stepsDir,
        step,
        fileName: entry.fileName,
        order: entry.order,
        total,
      });
      const generatePrompt = `${basePrompt}

====== 重要模式说明：仅生成单元测试 ======

当前运行在 \`--verify-generate-unittest\` 模式下，本轮任务只允许：
- 为当前步骤补充或生成单元测试代码；
- 运行必要的测试命令确认单元测试可执行；
- 在输出末尾附加包含 \`unit_test\` 字段的 JSON（与普通实现模式一致）。

禁止事项：
- 不要对业务实现代码做与测试无关的改动；
- 不要尝试实现新的功能逻辑，只针对已有实现编写或完善单元测试。`;

      const result = await callAnyAvailableAgent(generatePrompt, {
        cwd,
        verbose: true,
      });

      if (!result.success) {
        const errorMessage = result.error || "生成单元测试失败";
        console.log(chalk.red(`  ✗ 无法生成单元测试：${errorMessage}`));
        entry.finalStatus = step.status;
        entry.success = false;
        entry.error = errorMessage;
        firstFailure = firstFailure ?? entry;
        break;
      }

      const unitTest = extractUnitTestFromOutput(result.output);
      if (!unitTest) {
        const errorMessage = "AI 输出中未找到合法的 unit_test 配置";
        console.log(chalk.red(`  ✗ ${errorMessage}`));
        entry.finalStatus = step.status;
        entry.success = false;
        entry.error = errorMessage;
        firstFailure = firstFailure ?? entry;
        break;
      }

      step.unit_test = unitTest;
      entry.unitTest = unitTest;

      try {
        await fs.writeFile(entry.filePath, JSON.stringify(step, null, 2), "utf-8");
      } catch (err) {
        const message =
          err instanceof Error ? err.message : "无法写入步骤 JSON 文件";
        console.log(
          chalk.red(
            `✗ 步骤已成功生成单元测试，但写回状态到文件时失败：${message}`,
          ),
        );
        entry.finalStatus = step.status;
        entry.success = false;
        entry.error = message;
        firstFailure = firstFailure ?? entry;
        break;
      }

      console.log(
        chalk.green(
          `  ✓ 单元测试已生成并写入步骤 JSON（命令：${unitTest.command}）`,
        ),
      );

      entry.finalStatus = step.status;
      entry.success = true;
      entry.error = undefined;
      continue;
    }

    if (mode === "verify-unit-test-only") {
      console.log(
        chalk.gray(
          "  当前运行模式：仅执行 unit_test 中定义的单元测试，不做实现或 AI verification。",
        ),
      );

      if (!entry.unitTest || !entry.unitTest.command) {
        const errorMessage = "未配置 unit_test，无法执行单元测试";
        console.log(chalk.red(`  ✗ ${errorMessage}`));
        entry.finalStatus = step.status;
        entry.success = false;
        entry.error = errorMessage;
        firstFailure = firstFailure ?? entry;
        break;
      }

      console.log(
        chalk.gray(
          `  🧪 执行单元测试: ${entry.unitTest.command}`,
        ),
      );
      const testResult = await runUnitTestsForStep(entry.unitTest, cwd);
      if (!testResult.success) {
        console.log(chalk.red("  ✗ 单元测试失败"));
        if (testResult.error) {
          testResult.error
            .split("\n")
            .slice(0, 10)
            .forEach((line) => {
              if (line.trim()) {
                console.log(chalk.red(`    ${line}`));
              }
            });
        }

        if (step.status !== "🔴 待完成") {
          step.status = "🔴 待完成";
        }
        entry.finalStatus = step.status;
        entry.success = false;
        entry.error = "单元测试失败";

        try {
          await fs.writeFile(
            entry.filePath,
            JSON.stringify(step, null, 2),
            "utf-8",
          );
        } catch (err) {
          const message =
            err instanceof Error ? err.message : "无法写入步骤 JSON 文件";
          console.log(
            chalk.red(
              `✗ 无法写回失败状态到步骤文件：${message}`,
            ),
          );
        }

        firstFailure = firstFailure ?? entry;
        break;
      }

      console.log(chalk.green("  ✓ 单元测试通过"));
      entry.finalStatus = step.status;
      entry.success = true;
      entry.error = undefined;
      continue;
    }

    if (mode === "verify-only") {
      console.log(
        chalk.gray(
          "  当前运行模式：仅执行单元测试和 verification，不做实现改动。",
        ),
      );

      let testsFailed = false;
      let failureMessage: string | undefined;

      if (entry.unitTest && entry.unitTest.command) {
        console.log(
          chalk.gray(
            `  🧪 执行单元测试: ${entry.unitTest.command}`,
          ),
        );
        const testResult = await runUnitTestsForStep(entry.unitTest, cwd);
        if (!testResult.success) {
          console.log(chalk.red("  ✗ 单元测试失败"));
          if (testResult.error) {
            testResult.error
              .split("\n")
              .slice(0, 10)
              .forEach((line) => {
                if (line.trim()) {
                  console.log(chalk.red(`    ${line}`));
                }
              });
          }
          testsFailed = true;
          failureMessage = "单元测试失败";
        } else {
          console.log(chalk.green("  ✓ 单元测试通过"));
        }
      }

      if (!testsFailed) {
        const validationPrompt = buildRunStepValidationPrompt({
          projectRoot: cwd,
          stepsDir,
          step,
          fileName: entry.fileName,
          order: entry.order,
          total,
        });

        console.log(
          chalk.gray("  正在调用命令行 AI 按 verification 进行验证..."),
        );

        const validationResult = await callAnyAvailableAgent(
          validationPrompt,
          {
            cwd,
            verbose: true,
          },
        );

        if (!validationResult.success) {
          const verificationError =
            validationResult.error || "verification 验证失败";
          failureMessage = verificationError;
        } else {
          console.log(chalk.green("  ✓ verification 验证通过"));
        }
      }

      if (failureMessage) {
        console.log(chalk.red(`  ✗ 验证失败：${failureMessage}`));
        if (step.status !== "🔴 待完成") {
          step.status = "🔴 待完成";
        }
        entry.finalStatus = step.status;
        entry.success = false;
        entry.error = failureMessage;

        try {
          await fs.writeFile(
            entry.filePath,
            JSON.stringify(step, null, 2),
            "utf-8",
          );
        } catch (err) {
          const message =
            err instanceof Error ? err.message : "无法写回失败状态到步骤文件";
          console.log(
            chalk.red(
              `✗ 无法写回失败状态到步骤文件：${message}`,
            ),
          );
        }

        firstFailure = firstFailure ?? entry;
        break;
      }

      console.log(
        chalk.green("  ✓ 单元测试和 verification 均通过（未进行实现）。"),
      );
      entry.finalStatus = step.status;
      entry.success = true;
      entry.error = undefined;
      continue;
    }

    let needImplementation = step.status !== "🟢 已完成";

    // 如果当前为已完成状态，且开启了 fullVerify，则先进行一次「仅测试」的回归验证
    if (step.status === "🟢 已完成" && mode === "full-verify") {
      console.log(
        chalk.gray(
          "  当前步骤已标记为已完成，将仅重新运行测试进行回归验证...",
        ),
      );

      // 如果步骤包含 unit_test 信息，先按其内容运行单元测试
      if (entry.unitTest && entry.unitTest.command) {
        console.log(
          chalk.gray(
            `  🧪 执行单元测试: ${entry.unitTest.command}`,
          ),
        );
        const testResult = await runUnitTestsForStep(entry.unitTest, cwd);
        if (testResult.success) {
          console.log(chalk.green("  ✓ 单元测试通过"));
        } else {
          console.log(chalk.red("  ✗ 单元测试失败"));
          if (testResult.error) {
            testResult.error
              .split("\n")
              .slice(0, 10)
              .forEach((line) => {
                if (line.trim()) {
                  console.log(chalk.red(`    ${line}`));
                }
              });
          }

          entry.finalStatus = step.status;
          entry.success = false;
          entry.error = "单元测试失败";

          const now = new Date();
          await writeProgressMarkdown({
            stepsDir,
            entries,
            startedAt,
            finishedAt: now,
          });

          console.log(
            chalk.yellow(
              "  ⚠ 单元测试未通过，将重新打开该步骤并进入实现阶段...",
            ),
          );
          needImplementation = true;
        }
      }

      // 如果单元测试通过（或不存在），再调用 AI 按 verification 做回归验证
      if (!needImplementation) {
        const validationPrompt = buildRunStepValidationPrompt({
          projectRoot: cwd,
          stepsDir,
          step,
          fileName: entry.fileName,
          order: entry.order,
          total,
        });

        console.log(chalk.gray("  正在调用命令行 AI 进行回归测试验证..."));

        const validationResult = await callAnyAvailableAgent(validationPrompt, {
          cwd,
          verbose: true,
        });

        if (validationResult.success) {
          // 回归测试通过，保持状态为已完成，不进入实现阶段
          entry.finalStatus = step.status;
          entry.success = true;
          entry.error = undefined;
          console.log(
            chalk.green(
              "  ✓ 回归测试通过，保持状态为：🟢 已完成",
            ),
          );

          // 更新进度报告
          const now = new Date();
          await writeProgressMarkdown({
            stepsDir,
            entries,
            startedAt,
            finishedAt: now,
          });
          continue;
        }

        console.log(
          chalk.yellow(
            `  ⚠ 回归测试未通过或存在问题（${validationResult.error ?? "原因未知"}），将重新打开该步骤并进入实现阶段...`,
          ),
        );
        needImplementation = true;
      }
    }

    if (!needImplementation) {
      continue;
    }

    let shouldAbortRun = false;
    let lastFailureContext: PreviousAttemptFailureContext | undefined;

    for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
      const attemptStartStatus = step.status;
      // 标记为进行中
      const previousStatus = step.status;
      step.status = "🟡 进行中";
      entry.finalStatus = step.status;

      try {
        await fs.writeFile(
          entry.filePath,
          JSON.stringify(step, null, 2),
          "utf-8",
        );
      } catch (err) {
        const message =
          err instanceof Error ? err.message : "无法写入步骤 JSON 文件";
        console.log(
          chalk.red(
            `✗ 无法更新步骤文件 ${entry.fileName}: ${message}`,
          ),
        );
        entry.success = false;
        entry.error = message;
        firstFailure = firstFailure ?? entry;

        const now = new Date();
        await writeProgressMarkdown({
          stepsDir,
          entries,
          startedAt,
          finishedAt: now,
        });
        shouldAbortRun = true;
        break;
      }

      console.log(
        chalk.gray(
          `  状态更新: ${previousStatus} → ${step.status}`,
        ),
      );

      const attemptPrefix = `[${entry.order}/${total}]`;
      if (attempt === 1) {
        console.log(
          chalk.gray(
            `  🔁 ${attemptPrefix} 第 ${attempt}/${MAX_ATTEMPTS} 次尝试执行该步骤（首次尝试）...`,
          ),
        );
      } else {
        console.log(
          chalk.gray(
            `  🔁 ${attemptPrefix} 第 ${attempt}/${MAX_ATTEMPTS} 次尝试执行该步骤（上一轮失败，将基于失败原因进行修复）...`,
          ),
        );
      }

      const basePrompt = buildRunStepPrompt({
        projectRoot: cwd,
        stepsDir,
        step,
        fileName: entry.fileName,
        order: entry.order,
        total,
      });

      const prompt =
        attempt > 1 && lastFailureContext
          ? appendPreviousFailureContextToPrompt({
              basePrompt,
              context: lastFailureContext,
            })
          : basePrompt;

      console.log(chalk.gray("  正在调用命令行 AI 处理该步骤..."));

      const result = await callAnyAvailableAgent(prompt, {
        cwd,
        verbose: true,
      });

      if (result.success) {
        step.status = "🟢 已完成";
        entry.finalStatus = step.status;
        entry.success = true;
        entry.error = undefined;

        const unitTest = extractUnitTestFromOutput(result.output);
        if (unitTest) {
          step.unit_test = unitTest;
          entry.unitTest = unitTest;
          console.log(
            chalk.gray(
              `  单元测试信息已记录到步骤 JSON（命令：${unitTest.command}）`,
            ),
          );
        }

        try {
          await fs.writeFile(
            entry.filePath,
            JSON.stringify(step, null, 2),
            "utf-8",
          );
        } catch (err) {
          const message =
            err instanceof Error ? err.message : "无法写入步骤 JSON 文件";
          console.log(
            chalk.red(
              `✗ 步骤已成功执行，但写回状态到文件时失败：${message}`,
            ),
          );
          entry.success = false;
          entry.error = message;
          firstFailure = firstFailure ?? entry;
          shouldAbortRun = true;
          break;
        }

        console.log(
          chalk.green(
            `  ✓ 步骤执行成功，状态已更新为：${step.status}`,
          ),
        );

        // 普通 run 模式下，执行「单元测试 + verification 验证」
        if (mode !== "full-verify") {
          // 先执行单元测试（如果存在）
          if (entry.unitTest && entry.unitTest.command) {
            console.log(
              chalk.gray(
                `  🧪 执行单元测试: ${entry.unitTest.command}`,
              ),
            );
            const testResult = await runUnitTestsForStep(entry.unitTest, cwd);
            if (!testResult.success) {
              console.log(chalk.red("  ✗ 单元测试失败"));
              if (testResult.error) {
                testResult.error
                  .split("\n")
                  .slice(0, 10)
                  .forEach((line) => {
                    if (line.trim()) {
                      console.log(chalk.red(`    ${line}`));
                    }
                  });
              }

              const unitTestOutputSnippet = buildOutputSnippet(
                testResult.error || testResult.output || "",
              );

              step.status = "🔴 待完成";
              entry.finalStatus = step.status;
              entry.success = false;
              entry.error = "单元测试失败";

              lastFailureContext = {
                attempt,
                maxAttempts: MAX_ATTEMPTS,
                fromStatus: attemptStartStatus,
                toStatus: step.status,
                unitTestCommand: entry.unitTest.command,
                unitTestOutputSnippet,
              };

              if (lastFailureContext) {
                logAttemptFailureSummary(lastFailureContext);
              }

              try {
                await fs.writeFile(
                  entry.filePath,
                  JSON.stringify(step, null, 2),
                  "utf-8",
                );
              } catch {
                // 如果这里写回失败，错误已经在前面处理过，这里不再额外中断
              }

              const now = new Date();
              await writeProgressMarkdown({
                stepsDir,
                entries,
                startedAt,
                finishedAt: now,
              });

              if (attempt >= MAX_ATTEMPTS) {
                firstFailure = firstFailure ?? entry;
                shouldAbortRun = true;
                break;
              }

              // 未到最大重试次数，继续下一轮尝试
              continue;
            } else {
              console.log(chalk.green("  ✓ 单元测试通过"));
            }
          }

          // 再按 verification 列表让 AI 做一次验证
          const validationPrompt = buildRunStepValidationPrompt({
            projectRoot: cwd,
            stepsDir,
            step,
            fileName: entry.fileName,
            order: entry.order,
            total,
          });

          console.log(
            chalk.gray("  正在调用命令行 AI 按 verification 进行验证..."),
          );

          const validationResult = await callAnyAvailableAgent(
            validationPrompt,
            {
              cwd,
              verbose: true,
            },
          );

          if (!validationResult.success) {
            console.log(
              chalk.red(
                `  ✗ verification 验证未通过：${validationResult.error ?? "原因未知"}`,
              ),
            );

            const verificationError =
              validationResult.error || "verification 验证失败";

            step.status = "🔴 待完成";
            entry.finalStatus = step.status;
            entry.success = false;
            entry.error = verificationError;

            lastFailureContext = {
              attempt,
              maxAttempts: MAX_ATTEMPTS,
              fromStatus: attemptStartStatus,
              toStatus: step.status,
              verificationError,
            };

            if (lastFailureContext) {
              logAttemptFailureSummary(lastFailureContext);
            }

            try {
              await fs.writeFile(
                entry.filePath,
                JSON.stringify(step, null, 2),
                "utf-8",
              );
            } catch {
              // 同上，写回失败不再额外中断
            }

            const now = new Date();
            await writeProgressMarkdown({
              stepsDir,
              entries,
              startedAt,
              finishedAt: now,
            });

            if (attempt >= MAX_ATTEMPTS) {
              firstFailure = firstFailure ?? entry;
              shouldAbortRun = true;
              break;
            }

            // 未到最大重试次数，继续下一轮尝试
            continue;
          } else {
            console.log(chalk.green("  ✓ verification 验证通过"));
          }
        }

        if (mode !== "full-verify") {
          console.log(
            chalk.green(
              `  ✓ 第 ${attempt} 次尝试后步骤已通过所有测试与验证`,
            ),
          );
        }

        const now = new Date();
        await writeProgressMarkdown({
          stepsDir,
          entries,
          startedAt,
          finishedAt: now,
        });

        // 当前轮次实现 + 验证均成功，结束重试循环
        break;
      } else {
        step.status = "🔴 待完成";
        entry.finalStatus = step.status;
        entry.success = false;
        const aiError = result.error || "AI 子进程执行失败";
        entry.error = aiError;

        lastFailureContext = {
          attempt,
          maxAttempts: MAX_ATTEMPTS,
          fromStatus: attemptStartStatus,
          toStatus: step.status,
          aiError,
        };

        if (lastFailureContext) {
          logAttemptFailureSummary(lastFailureContext);
        }

        try {
          await fs.writeFile(
            entry.filePath,
            JSON.stringify(step, null, 2),
            "utf-8",
          );
        } catch (err) {
          const message =
            err instanceof Error ? err.message : "无法写回失败状态到步骤文件";
          console.log(
            chalk.red(
              `✗ 无法写回失败状态到步骤文件：${message}`,
            ),
          );
        }

        console.log(
          chalk.red(
            `✗ 步骤执行失败：${entry.error}`,
          ),
        );

        const now = new Date();
        await writeProgressMarkdown({
          stepsDir,
          entries,
          startedAt,
          finishedAt: now,
        });

        if (attempt >= MAX_ATTEMPTS) {
          firstFailure = firstFailure ?? entry;
          shouldAbortRun = true;
          break;
        }

        // 未到最大重试次数，继续下一轮尝试
        continue;
      }
    }

    if (shouldAbortRun) {
      break;
    }
  }

  const successCount = entries.filter((e) => e.success).length;
  const totalSteps = entries.length;

  console.log("");
  console.log(
    chalk.bold(
      `📋 本次 run 执行结果：${successCount}/${totalSteps} 个步骤执行成功`,
    ),
  );

  if (firstFailure) {
    console.log(
      chalk.red(
        `✗ 第一个失败的步骤：${firstFailure.fileName}${
          firstFailure.id ? ` (${firstFailure.id})` : ""
        }`,
      ),
    );
    if (firstFailure.error) {
      console.log(chalk.red(`  错误原因：${firstFailure.error}`));
    }
    process.exitCode = 1;
  } else {
    console.log(chalk.green("✓ 所有步骤均已成功执行"));
  }

  const finishedAt = new Date();
  const progressPath = await writeProgressMarkdown({
    stepsDir,
    entries,
    startedAt,
    finishedAt,
  });
  console.log(chalk.gray(`  执行进度报告已写入：${progressPath}`));
}
