/**
 * Core type definitions for agent-foreman
 * Long Task Harness for AI agents
 */

// ============================================================================
// Feature Types
// ============================================================================

/**
 * Feature status values
 * - failing: Not yet implemented or incomplete
 * - passing: Acceptance criteria met
 * - blocked: External dependency blocking progress
 * - needs_review: Potentially affected by recent changes
 * - deprecated: No longer needed, superseded by another feature
 */
export type FeatureStatus =
  | "failing"
  | "passing"
  | "blocked"
  | "needs_review"
  | "deprecated";

/**
 * How the feature was created/discovered
 */
export type FeatureOrigin =
  | "init-auto" // Auto-generated during init
  | "init-from-routes" // Derived from route definitions
  | "init-from-tests" // Derived from test files
  | "manual" // Manually added by user
  | "replan"; // Added during replanning

/**
 * Summary of verification result to embed in Feature
 */
export interface FeatureVerificationSummary {
  /** Last verification timestamp (ISO 8601) */
  verifiedAt: string;
  /** Verification verdict */
  verdict: "pass" | "fail" | "needs_review";
  /** Agent that performed verification */
  verifiedBy: string;
  /** Git commit hash at verification time */
  commitHash?: string;
  /** Brief summary of the verification result */
  summary: string;
}

/**
 * Unit test requirements for TDD workflow
 */
export interface UnitTestRequirements {
  /** Whether unit tests are required for this feature */
  required: boolean;
  /** Glob pattern for test files */
  pattern?: string;
  /** Expected test case names derived from acceptance criteria */
  cases?: string[];
}

/**
 * E2E test requirements for TDD workflow
 */
export interface E2ETestRequirements {
  /** Whether E2E tests are required for this feature */
  required: boolean;
  /** Glob pattern for E2E test files */
  pattern?: string;
  /** Playwright tags for filtering */
  tags?: string[];
  /** Expected scenario names derived from acceptance criteria */
  scenarios?: string[];
}

/**
 * Test requirements for TDD workflow
 * When defined, verification uses test execution instead of AI analysis
 */
export interface TestRequirements {
  /** Unit test requirements */
  unit?: UnitTestRequirements;
  /** E2E test requirements */
  e2e?: E2ETestRequirements;
}

/**
 * Cached TDD guidance generated by AI
 * Stored in feature to avoid regeneration
 */
export interface CachedTDDGuidance {
  /** Generation timestamp (ISO 8601) */
  generatedAt: string;
  /** Agent that generated this (claude/gemini/codex) */
  generatedBy: string;
  /** Feature version when generated (for invalidation) */
  forVersion: number;
  /** Suggested test file paths */
  suggestedTestFiles: {
    unit: string[];
    e2e: string[];
  };
  /** Unit test cases with assertions */
  unitTestCases: Array<{
    name: string;
    assertions: string[];
  }>;
  /** E2E scenarios (if applicable) */
  e2eScenarios: Array<{
    name: string;
    steps: string[];
  }>;
  /** Detected/suggested test framework */
  frameworkHint?: string;
}

/**
 * Single feature entry in the feature list
 */
export interface Feature {
  /** Unique identifier, e.g., "chat.message.edit" */
  id: string;
  /** Human-readable description */
  description: string;
  /** Parent module/subsystem */
  module: string;
  /** Priority (1 = highest) */
  priority: number;
  /** Current status */
  status: FeatureStatus;
  /** List of acceptance criteria */
  acceptance: string[];
  /** Feature IDs this feature depends on */
  dependsOn: string[];
  /** Feature IDs this feature replaces */
  supersedes: string[];
  /** Categorization tags */
  tags: string[];
  /** Increments when description changes */
  version: number;
  /** How this feature was created */
  origin: FeatureOrigin;
  /** Additional context or notes */
  notes: string;
  /** Last verification result (optional) */
  verification?: FeatureVerificationSummary;
  /**
   * E2E test tags for selective E2E test execution (optional)
   * Array of Playwright test tags to filter E2E tests
   * Used with Playwright's --grep flag for tag-based filtering
   *
   * Semantic meaning:
   * - undefined or not set: Skip E2E tests (feature has no UI)
   * - []: Skip E2E tests (explicit no-UI marker)
   * - ["@smoke"]: Run smoke E2E tests
   * - ["@feature-auth", "@login"]: Run specific feature E2E tests
   * - ["*"]: Run all E2E tests
   */
  e2eTags?: string[];
  /**
   * Test requirements for TDD workflow (optional)
   * When defined, verification uses test execution instead of AI analysis
   */
  testRequirements?: TestRequirements;
  /**
   * Actual test files created for this feature (written back after complete)
   * Populated by the complete command after verification passes
   */
  testFiles?: string[];
  /**
   * Cached TDD guidance from AI (optional)
   * Regenerated when feature.version changes
   */
  tddGuidance?: CachedTDDGuidance;
}

/**
 * Get the effective test pattern for a feature
 * Uses testRequirements.unit.pattern if available
 *
 * @param feature - The feature to get test pattern from
 * @returns Test pattern string or undefined
 */
export function getTestPattern(feature: Feature): string | undefined {
  return feature.testRequirements?.unit?.pattern;
}

/**
 * Feature list file structure (ai/feature_list.json)
 */
export interface FeatureList {
  /** JSON Schema reference */
  $schema?: string;
  /** Array of features */
  features: Feature[];
  /** File metadata */
  metadata: FeatureListMetadata;
}

export interface FeatureListMetadata {
  /** Project goal description */
  projectGoal: string;
  /** ISO 8601 timestamp of creation */
  createdAt: string;
  /** ISO 8601 timestamp of last update */
  updatedAt: string;
  /** Schema version */
  version: string;
}

// ============================================================================
// Progress Log Types
// ============================================================================

/**
 * Progress log entry types
 * - INIT: Initial harness creation
 * - STEP: Feature implementation step
 * - CHANGE: Feature status change
 * - REPLAN: Major replanning event
 * - VERIFY: Feature verification result
 */
export type ProgressLogType = "INIT" | "STEP" | "CHANGE" | "REPLAN" | "VERIFY";

/**
 * Progress log entry structure
 */
export interface ProgressLogEntry {
  /** Entry type */
  type: ProgressLogType;
  /** ISO 8601 timestamp */
  timestamp: string;
  /** Feature ID (for STEP/CHANGE) */
  feature?: string;
  /** New status (for STEP) */
  status?: FeatureStatus;
  /** Action taken (for CHANGE) */
  action?: string;
  /** Reason for the entry */
  reason?: string;
  /** Test command that was run */
  tests?: string;
  /** Brief summary */
  summary: string;
  /** Project goal (for INIT) */
  goal?: string;
  /** Additional notes */
  note?: string;
}

// ============================================================================
// Project Survey Types
// ============================================================================

/**
 * Detected tech stack information
 */
export interface TechStackInfo {
  /** Primary programming language */
  language: string;
  /** Framework (e.g., express, vue, echo) */
  framework: string;
  /** Build tool (e.g., vite, webpack, go build) */
  buildTool: string;
  /** Test framework (e.g., vitest, jest, go test) */
  testFramework: string;
  /** Package manager (e.g., npm, pnpm, go mod) */
  packageManager: string;
}

/**
 * Directory structure analysis
 */
export interface DirectoryStructure {
  /** Entry point files */
  entryPoints: string[];
  /** Source directories */
  srcDirs: string[];
  /** Test directories */
  testDirs: string[];
  /** Configuration files */
  configFiles: string[];
}

/**
 * Module information
 */
export interface ModuleInfo {
  /** Module name */
  name: string;
  /** Relative path */
  path: string;
  /** Module description */
  description: string;
  /** Files in this module */
  files: string[];
  /** Completion status */
  status: "complete" | "partial" | "stub";
}

/**
 * Discovered feature from project scanning
 */
export interface DiscoveredFeature {
  /** Generated feature ID */
  id: string;
  /** Description from source */
  description: string;
  /** Inferred module */
  module: string;
  /** Source of discovery */
  source: "route" | "test" | "controller" | "model" | "inferred" | "feature_list";
  /** Confidence score (0-1) */
  confidence: number;
  /** Actual status from feature_list.json (optional) */
  status?: FeatureStatus;
}

/**
 * Completion assessment
 */
export interface CompletionAssessment {
  /** Overall completion percentage (0-100) */
  overall: number;
  /** Completion by module */
  byModule: Record<string, number>;
  /** Assessment notes */
  notes: string[];
}

/**
 * Project commands
 */
export interface ProjectCommands {
  /** Install dependencies command */
  install: string;
  /** Start development server command */
  dev: string;
  /** Build for production command */
  build: string;
  /** Run tests command */
  test: string;
  /** Lint command (optional) */
  lint?: string;
}

/**
 * Complete project survey result
 */
export interface ProjectSurvey {
  /** Detected tech stack */
  techStack: TechStackInfo;
  /** Directory structure */
  structure: DirectoryStructure;
  /** Discovered modules */
  modules: ModuleInfo[];
  /** Discovered features */
  features: DiscoveredFeature[];
  /** Completion assessment */
  completion: CompletionAssessment;
  /** Available commands */
  commands: ProjectCommands;
}

// ============================================================================
// CLI Types
// ============================================================================

/**
 * Init harness modes
 * - merge: Keep existing features, add new discoveries
 * - new: Backup old list, create fresh
 * - scan: Preview only, no modifications
 */
export type InitMode = "merge" | "new" | "scan";

/**
 * Survey command options
 */
export interface SurveyOptions {
  /** Output path for survey markdown */
  output?: string;
  /** Show detailed output */
  verbose?: boolean;
}

/**
 * Init command options
 */
export interface InitOptions {
  /** Init mode */
  mode: InitMode;
  /** Show detailed output */
  verbose?: boolean;
}

/**
 * Step command options
 */
export interface StepOptions {
  /** Specific feature ID to work on */
  featureId?: string;
  /** Show plan without executing */
  dryRun?: boolean;
}

// ============================================================================
// Impact Analysis Types
// ============================================================================

/**
 * Impact analysis result
 */
export interface ImpactResult {
  /** Features directly dependent on the changed feature */
  directlyAffected: Feature[];
  /** Features in the same module that might be affected */
  potentiallyAffected: Feature[];
  /** Recommended actions */
  recommendations: ImpactRecommendation[];
}

/**
 * Impact recommendation
 */
export interface ImpactRecommendation {
  /** Feature ID to act on */
  featureId: string;
  /** Recommended action */
  action: "mark_needs_review" | "mark_deprecated" | "update_notes";
  /** Reason for recommendation */
  reason: string;
}
