/**
 * Harness documentation prompt templates
 *
 * With the modular .claude/rules/ approach, this module only provides
 * minimal CLAUDE.md generation. The harness documentation is now in
 * separate rule files that Claude Code loads automatically.
 */

/**
 * Generate minimal CLAUDE.md content (used with modular rules)
 * When rules are in .claude/rules/, CLAUDE.md only needs project-specific content
 */
export function generateMinimalClaudeMd(goal: string): string {
  return `# Project Instructions

## Project Goal

${goal}

---

*Harness documentation is in \`.claude/rules/\` - loaded automatically by Claude Code*
`;
}

/**
 * Generate minimal AGENTS.md content for a project (OpenCode)
 *
 * This is the OpenCode equivalent of CLAUDE.md.
 * Rules are loaded from .opencode/rules/ directory via opencode.json.
 */
export function generateMinimalAgentsMd(goal: string): string {
  return `# Project Instructions

## Project Goal

${goal}

---

*This project uses agent-foreman. Rules are loaded from .opencode/rules/*
*Generated by agent-foreman - https://github.com/mylukin/agent-foreman*
`;
}
